model:
  run_name: "Provolone"
  name: "QNN1"
  load: False # False or the name of the model
  save: True # for overwriting

alpha1:
  enabled: False

alpha2: 
  enabled: False

alpha3: 
  enabled: False

alpha4:
  enabled: True
  pretraining:
    doit: True
    batch_size: 516
    epochs: 2
    learning_rate: 0.001
    data_path: "data/data_01_15.pgn"
  training: 
    doit: True
    batch_size: 64
    episodes: 1000

alpha5: 
  enabled: False

alpha6: 
  enabled: False


