model:
  run_name: "Provolone"
  name: "QNN1"
  load: False # False or the name of the model
  save: True # for overwriting

data:
  data_path: "data/data_01_15.pgn"

pretraining:
  enabled: True
  batch_size: 256
  epochs: 2
  learning_rate: 0.001

training:
  enabled: True
  episodes: 1000
  batch_size: 32
