model:
  name: "MyNeuralNet"
  layers: 3
  units_per_layer: [64, 128, 256]
  activation: "relu"

training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001

data:
  train_data_path: "data/processed/train.csv"
  validation_data_path: "data/processed/val.csv"
