_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.2
            "8":
                - 5
            "12": 0.18.2
            "13": linux-x86_64
batch_size:
    value: 64
epsilon_decay:
    value: 1000000
epsilon_end:
    value: 0.4
epsilon_start:
    value: 1
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
memory_capacity:
    value: 100000
num_episodes:
    value: 15000
target_update:
    value: 1000
